config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  get '/posts/new', to: 'posts#new', as: 'create_post'
  post '/posts/new', to: 'posts#create'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'post'
  post '/users/:user_id/posts/:id/', to: 'comments#create'
  post '/users/:user_id/posts/:id/likes', to: 'posts#create_like', as: 'like'
  
  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only:[:destroy]
    end
  end


   # API routes
   namespace :api do
    namespace :v1 do
      resources :users do 
        resources :posts do 
          resources :comments
          resources :likes
        end
      end
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :posts_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }

  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  # User::Roles
  # The available roles
  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  def recent_three
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  before_action :set_author, only: [:show]

  def index
    authors = User.all.order(:id)
    render json: authors, status: :ok
  end

  def show
    render json: @author, status: :ok
  end

  private

  def set_author
    @author = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  # index and show actions are the same as in app\controllers\posts_controller.rb
  def index
    @users = User.all.order(:id)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<%= link_to user_path(user) do %>
  <li class="user-list">
    <div class="user-image">
      <%= image_tag user.photo, alt: "#{user.name}-avatar", class: 'profile-image' %>
    </div>
    <div class="user-info">
      <h3 class="username"><%= user.name %></h3>
      <span class="post-counter">Number of posts: <%= user.posts_counter %></span>
    </div>
  </li>
<% end %>

app/views/users/index.html.erb
<% content_for :title, "Blog App" %>
<section class="users-container">
  <% @users.each do |user| %>
    <%= render "user", user: user %>
  <% end %>

  <div class="create-post">
    <%= link_to create_post_path do %>
      <button>create post</button>
    <%end%>
  </div>
</section>

app/views/users/show.html.erb
<% content_for :title, "#{@user.name}'s - Blog" %>
<section class="user-details-section">
  <%= render "user", user: @user %>
  <div class="bio">
    <h3>Bio<h3>
    <p class='bio-desc'><%= @user.bio %></p>
  </div>

  <% @user.recent_three.each do |post| %>
    <%= link_to user_post_path(@user, post) do %>
      <%= render "posts/post", post: post %>
    <% end %>
  <% end %>
  
  <%= link_to user_posts_path(@user), class: 'self-center' do %>
    <button type="button" class="see-all-posts">See all posts</button>
  <% end %>
</section>