config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  get '/posts/new', to: 'posts#new', as: 'create_post'
  post '/posts/new', to: 'posts#create'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'post'
  post '/users/:user_id/posts/:id/', to: 'comments#create'
  post '/users/:user_id/posts/:id/likes', to: 'posts#create_like', as: 'like'
  
  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only:[:destroy]
    end
  end


   # API routes
   namespace :api do
    namespace :v1 do
      resources :users do 
        resources :posts do 
          resources :comments
          resources :likes
        end
      end
    end
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :update_posts_counter
  after_destroy :update_posts_counter

  validates :title, presence: true, length: { in: 1..250 }
  validates :comments_counter, :likes_counter, comparison: { greater_than_or_equal_to: 0 },
                                               numericality: { only_integer: true }

  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def recent_five
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.all.length)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  before_action :set_author, only: %i[index show]
  before_action :set_post, only: [:show]

  def index
    posts = @author.posts
    render json: posts, status: :ok
  end

  def show
    render json: @post, status: :ok
  end

  private

  def set_author
    @author = User.find(params[:user_id])
  end

  def set_post
    @post = set_author.posts.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # This method is used to show all posts.
  def index
    @user = User.find(params[:user_id])
  end

  # This method is used to show a specific post.
  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments.includes([:author])
    @like = Like.new
  end

  # This method is used to create a new comment.
  def create_comment
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:id])
    @comment.author = current_user
    redirect_to post_path if @comment.save
  end

  # This method is used to create a new like.
  def create_like
    @like = Like.new(author: current_user, post: Post.find(params[:id]))
    redirect_to post_path if @like.save
  end

  # This method is used to delete a post.
  def destroy
    post = Post.find(params[:id])
    flash[:notice] = post.destroy ? 'Post was successfully deleted.' : 'Error: Post could not be deleted'

    redirect_to user_posts_url
  end

  # This method is used to create a new post.
  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.likes_counter = 0
    @post.comments_counter = 0
    flash[:notice] = @post.save ? 'Post have been saved successfully' : 'Login'

    redirect_to posts_new_path
  end

  # This method is used to show the new post form.
  def new
    @post = Post.new
  end

  private

  # only allow a list of trusted parameters through
  def post_params
    params.require(:post).permit(:title, :text)
  end

  # only allow a list of trusted parameters through
  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="user-post">
  <div class="post-title">
    <h3><%= post.title %></h3>
    <p><%= post.text %></p>
  </div>
  <aside class="counter-section">
    <span>Comments: <%= post.comments_counter %></span>
    <span>Likes: <%= post.likes_counter %></span>
  <aside>
</div>

app/views/posts/_user_post.html.erb
<div class="user-post">
  <div class="title">
    <h3> <%= post.title %> by <%= post.author.name %> </h3>
    <aside class="counter-section">
      <span>Comments: <%= post.comments_counter %></span>
      <span>Likes: <%= post.likes_counter %></span>
    <aside>
  </div>
  <div class="post-like-section">
  <p><%= post.text %></p>
  <% if user_signed_in?  %>
    <div class="button-section">
    <%= button_to "Add Like", like_path(@user, @post), class: "button button-text button-pink", 'data-ripple-light': true, method: :post %>
    <% if can? :destroy, @post %>
      <%= button_to "Delete Post", user_post_path, method: :delete, class: "m-3 p-1 button-gradient text-lg text-white bg-gray-700 border hover:text-gray-700 hover:border-gray-700 hover:bg-transparent", 'data-ripple-light': true %>
    <% end %>
    </div>
  <% else %>
  <%= button_to "Add Like", new_user_session_url, class: "bg-red-400", class: "button button-text button-pink", 'data-ripple-light': true, method: :get %>
  <% end %>
</div>
</div>

app/views/posts/index.html.erb
<section class="post-section">
<% content_for :title, "#{@user.name}'s Posts" %>
<%= render "users/user", user: @user %>
<% @user.posts.each do | post | %>
  <%= link_to user_post_path(@user, post) do %>
    <%= render "post", post: post %>
    
    <div class="user-post-comments">
      <h3 class="text-xl">
      <span class="comments">Comments</span>
      <span>for Post: </span>
      <span class="comment-title"><%="#{post.title}"%> </span>
      </h3>
      <% post.recent_five.includes([:author]).each do |comment| %>
        <div class="post-comment">
          <p>
            <span><strong><%= comment.author.name %>:</strong></span>
            <span><%= comment.text %></span>
          </p>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>
</section>

app/views/posts/new.html.erb
<div class="container">
<% if notice %>
  <div class="notice"><%= notice %></div>
<% end %>
</div>
<div class="post-container">
  <h1>Create New Post</h1>

  <%= form_with model: @post, url: posts_new_path, method: :post, scope: :post do |f| %>
    <div class="column">
    <%= f.text_field :title, placeholder: 'Title of post', class: 'text-input' %>
    <%= f.text_area :text,placeholder: 'Description of post' %>
    <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<% content_for :title, "#{@user.name} | #{@post.title}" %>
<div class="container">
<% if flash[notice:] %>
  <div class="notice"><%= flash[notice:] %></div>
<% end %>
</div>
<%= render "user_post", post: @post %>
<div class="post-comments">
  <% @comments.each do |comment| %>
    <div class="post-comment">
      <p class="comment-area">
        <span><strong><%= comment.author.name %>:</strong></span>
        <span><%= comment.text %></span>
      </p>
      <% if can? :destroy, comment %>
        <%= button_to "Delete Comment", user_post_comment_path(@user, @post, comment), method: :delete, class: "p-1 chip capitalize text-sm text-white bg-red-500 border hover:text-red-500 hover:border-red-500 hover:bg-transparent", 'data-ripple-light': true %>
      <% end %>
    </div>
  <% end %>
<div>

<%= form_with model: @comment, url: post_path, method: :post, scope: :comment do |f| %>
  <div class="comment-section">
    <%= f.text_area :text, placeholder: "Add Comment" %>
    <%= f.submit "Comment" %>
  </div>
  <% end %>